### ISSUE TITLE
Re-add PDF generation

### ISSUE THREAD

**Issue by nuest** [o2r-project/api#90]
https://stackoverflow.com/questions/54259816/how-to-generate-a-pdf-or-markup-from-openapi-3-0

This is the old make target for PDF generation of the mkdocs-based site:

```Makefile
pdf: build
	wkhtmltopdf --version;
	# fix protocol relative URLs, see https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2713
	find site/ -type f -name '*.html' | xargs sed -i 's|href="//|href="https://|g'
	find site/ -type f -name '*.html' | xargs sed -i 's|src="//|src="https://|g'
	wkhtmltopdf --margin-top 20mm --no-background --javascript-delay 5000 \
	file://$(shell pwd)/site/index.html \
	file://$(shell pwd)/site/compendium/view/index.html \
	file://$(shell pwd)/site/compendium/candidate/index.html \
	file://$(shell pwd)/site/compendium/files/index.html \
	file://$(shell pwd)/site/compendium/delete/index.html \
	file://$(shell pwd)/site/compendium/upload/index.html \
	file://$(shell pwd)/site/compendium/public_share/index.html \
	file://$(shell pwd)/site/compendium/download/index.html \
	file://$(shell pwd)/site/compendium/metadata/index.html \
	file://$(shell pwd)/site/compendium/substitute/index.html \
	file://$(shell pwd)/site/compendium/link/index.html \
	file://$(shell pwd)/site/job/index.html \
	file://$(shell pwd)/site/search/index.html \
	file://$(shell pwd)/site/shipment/index.html \
	file://$(shell pwd)/site/user/index.html \
	o2r-web-api.pdf
```

**Comment by nuest** [comment]
PDF should be integrated into the reproducibility-service large repo, too.

**Comment by Fmazin** [comment]
An overview of possible solutions: 

| |RapiPDF|SwDoc|widdershins + mdpdf|
|---|---|---|---|
|Format| npm Package and CDN| Website Converter| 2 npm Packages|
|License|MIT|???|MIT and Apache-2.0|
|Github Links|[Link](https://github.com/mrin9/RapiPdf)|[Link](https://github.com/Irdis/SwDoc)|[widdershins](https://github.com/Mermade/widdershins), [mdpdf](https://github.com/bluehatbrit/mdpdf#readme)|
|conversion process|button on [HTML page](https://mrin9.github.io/RapiPdf/)|form element on [website](https://www.swdoc.org/)| Two CLI commands `mdpdf myOutput.md` and `mdpdf myOutput.md`|
|Advantages| <ul><li>Produces nice PDF</li><li>Some customization options</li></ul> | It works after all...| <ul><li>Easier implementation than Action (CLI)</li><li>Many customization options</li></ul>|
|Disadvantages| <ul><li>CLI implementation not easy; no CLI; probably possible via npm but difficult</li><li>Documentation sparse</li></ul>|<ul><li>Unordered PDF; Topic blocks are torn apart</li><li>no customization at all</li><li>no documentation at all</li><li>Written in C# (I can't) | <ul><li>PDF is a bit messy => Would have to be rejigged via options</li></ul>|
|Example PDF|[PDF](https://uni-muenster.sciebo.de/s/7L3ts8nOlKQaYTu) |[PDF](https://uni-muenster.sciebo.de/s/9eweh6AKPWaLbNc)|[PDF](https://uni-muenster.sciebo.de/s/oCfoYFPEmL7jest)|

**Comment by Fmazin** [comment]
After further discussion with @nuest we agreed on the option widdershins + mdpdf

**Comment by Fmazin** [comment]
I have made naive concept for the action after getting myself familiar with the actions: 

![gh_action](https://user-images.githubusercontent.com/48436261/111330756-845bcd00-8670-11eb-9a79-ab939ae8f5cf.png)

I have few question:
1. Is this possible?
2. Which version of ubuntu?
2. Which version of node?

**Comment by nuest** [comment]
1. Looks possible to me. I'd say for removing the file, you don't need to use a specific action but can just use `run: rm ./docs/*.md`
2. The latest one, `20.04` probably?
3. Use the latest stable release, `14` (with `check-latest: false`, that should make things a little bit faster, see https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#language-and-runtime)
