### ISSUE TITLE
Check if timestamps are correctly documented

### ISSUE THREAD

**Issue by nuest** [o2r-project/api#94]
See branch https://github.com/o2r-project/api/tree/timestamps (last two commits).

If everything is in the OpenAPI spec, then tell @nuest the branch `timestamps` can be deleted.

**Comment by nuest** [comment]
Move the "metadata" stuff from https://o2r.info/api/#section/Execute-a-compendium into "View single job", rename "Status" to "Step status" to better distinguish from "Job status".

**Comment by Fmazin** [comment]
I have moved the step metadata to the view single job and renamed the status to Step Status. 

![Bildschirmfoto von 2021-01-08 17-22-04](https://user-images.githubusercontent.com/48436261/104039259-6ee0a780-51d6-11eb-80f2-64cf548697cf.png)
Currently it would look like this:
